name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Run linters
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        version: v1.29
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16

      - name: Check out code
        uses: actions/checkout@v2.3.4

      - name: Run Unit tests.
        run: go test ./... -cover

  coverage:
    name: covarage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
  release:
    runs-on: ubuntu-latest
    needs: [golangci, test]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GH_PRIVATE_TOKEN }}
